"""Export the supplied MATLAB shock arrays losslessly to dependency-free Julia.

Run from any directory with Python + SciPy. This conversion is not needed to
execute the notebook; shocks.jl is committed and checked against the MAT hash.
"""
from pathlib import Path
import hashlib
from scipy.io import loadmat

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "reference/MatlabCode_overborrowingAER_web/proc_shock.mat"
data = loadmat(SOURCE)
fmt = lambda x: format(float(x), ".17g")
lines = [
    "# Generated by export_shocks.py from the original replication package.",
    f'const SHOCK_FILE_SHA256 = "{hashlib.sha256(SOURCE.read_bytes()).hexdigest()}"',
    "function original_shocks()",
]
for key in ("yT", "yN"):
    lines.append(f"    {key} = [" + ", ".join(map(fmt, data[key].ravel())) + "]")
lines.append("    Pi = [")
lines.extend("        " + " ".join(map(fmt, row)) + ";" for row in data["Prob"])
lines += ["    ]", "    return yT, yN, Pi", "end", ""]
Path(__file__).with_name("shocks.jl").write_text("\n".join(lines), encoding="utf-8")
print("Exported 16 shock states and 256 transition probabilities at Float64 precision.")
